# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Dec  3 02:59:11 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.teLog = QtGui.QPlainTextEdit(self.centralwidget)
        self.teLog.setEnabled(True)
        self.teLog.setGeometry(QtCore.QRect(0, 0, 581, 551))
        self.teLog.setObjectName(_fromUtf8("teLog"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(590, 1, 177, 510))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblTicketsNum = QtGui.QLabel(self.widget)
        self.lblTicketsNum.setObjectName(_fromUtf8("lblTicketsNum"))
        self.verticalLayout.addWidget(self.lblTicketsNum)
        self.leTicketsNum = QtGui.QLineEdit(self.widget)
        self.leTicketsNum.setObjectName(_fromUtf8("leTicketsNum"))
        self.verticalLayout.addWidget(self.leTicketsNum)
        self.lblGenExpVal = QtGui.QLabel(self.widget)
        self.lblGenExpVal.setObjectName(_fromUtf8("lblGenExpVal"))
        self.verticalLayout.addWidget(self.lblGenExpVal)
        self.leGenExpVal = QtGui.QLineEdit(self.widget)
        self.leGenExpVal.setObjectName(_fromUtf8("leGenExpVal"))
        self.verticalLayout.addWidget(self.leGenExpVal)
        self.lblProcExpVal = QtGui.QLabel(self.widget)
        self.lblProcExpVal.setObjectName(_fromUtf8("lblProcExpVal"))
        self.verticalLayout.addWidget(self.lblProcExpVal)
        self.leProcExpVal = QtGui.QLineEdit(self.widget)
        self.leProcExpVal.setObjectName(_fromUtf8("leProcExpVal"))
        self.verticalLayout.addWidget(self.leProcExpVal)
        self.lblProcDiap = QtGui.QLabel(self.widget)
        self.lblProcDiap.setObjectName(_fromUtf8("lblProcDiap"))
        self.verticalLayout.addWidget(self.lblProcDiap)
        self.leProcDiap = QtGui.QLineEdit(self.widget)
        self.leProcDiap.setObjectName(_fromUtf8("leProcDiap"))
        self.verticalLayout.addWidget(self.leProcDiap)
        self.lblQueueSize = QtGui.QLabel(self.widget)
        self.lblQueueSize.setObjectName(_fromUtf8("lblQueueSize"))
        self.verticalLayout.addWidget(self.lblQueueSize)
        self.leQueueSize = QtGui.QLineEdit(self.widget)
        self.leQueueSize.setObjectName(_fromUtf8("leQueueSize"))
        self.verticalLayout.addWidget(self.leQueueSize)
        self.lblDt = QtGui.QLabel(self.widget)
        self.lblDt.setObjectName(_fromUtf8("lblDt"))
        self.verticalLayout.addWidget(self.lblDt)
        self.leDeltaT = QtGui.QLineEdit(self.widget)
        self.leDeltaT.setObjectName(_fromUtf8("leDeltaT"))
        self.verticalLayout.addWidget(self.leDeltaT)
        self.lblEps = QtGui.QLabel(self.widget)
        self.lblEps.setObjectName(_fromUtf8("lblEps"))
        self.verticalLayout.addWidget(self.lblEps)
        self.leEps = QtGui.QLineEdit(self.widget)
        self.leEps.setObjectName(_fromUtf8("leEps"))
        self.verticalLayout.addWidget(self.leEps)
        self.rbWithoutReturn = QtGui.QRadioButton(self.widget)
        self.rbWithoutReturn.setChecked(True)
        self.rbWithoutReturn.setObjectName(_fromUtf8("rbWithoutReturn"))
        self.verticalLayout.addWidget(self.rbWithoutReturn)
        self.rbWithReturn = QtGui.QRadioButton(self.widget)
        self.rbWithReturn.setObjectName(_fromUtf8("rbWithReturn"))
        self.verticalLayout.addWidget(self.rbWithReturn)
        self.pbDt = QtGui.QPushButton(self.widget)
        self.pbDt.setObjectName(_fromUtf8("pbDt"))
        self.verticalLayout.addWidget(self.pbDt)
        self.pbEvent = QtGui.QPushButton(self.widget)
        self.pbEvent.setObjectName(_fromUtf8("pbEvent"))
        self.verticalLayout.addWidget(self.pbEvent)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Моделирование очереди", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTicketsNum.setText(QtGui.QApplication.translate("MainWindow", "Число заявок", None, QtGui.QApplication.UnicodeUTF8))
        self.leTicketsNum.setText(QtGui.QApplication.translate("MainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGenExpVal.setText(QtGui.QApplication.translate("MainWindow", "Матожидание генератора", None, QtGui.QApplication.UnicodeUTF8))
        self.leGenExpVal.setText(QtGui.QApplication.translate("MainWindow", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProcExpVal.setText(QtGui.QApplication.translate("MainWindow", "Матожидание обработчика", None, QtGui.QApplication.UnicodeUTF8))
        self.leProcExpVal.setText(QtGui.QApplication.translate("MainWindow", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProcDiap.setText(QtGui.QApplication.translate("MainWindow", "Полуинтервал обработчика", None, QtGui.QApplication.UnicodeUTF8))
        self.leProcDiap.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.lblQueueSize.setText(QtGui.QApplication.translate("MainWindow", "Размер очереди", None, QtGui.QApplication.UnicodeUTF8))
        self.leQueueSize.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDt.setText(QtGui.QApplication.translate("MainWindow", "delta_t", None, QtGui.QApplication.UnicodeUTF8))
        self.leDeltaT.setText(QtGui.QApplication.translate("MainWindow", "0.01", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEps.setText(QtGui.QApplication.translate("MainWindow", "Eps", None, QtGui.QApplication.UnicodeUTF8))
        self.leEps.setText(QtGui.QApplication.translate("MainWindow", "0.005", None, QtGui.QApplication.UnicodeUTF8))
        self.rbWithoutReturn.setText(QtGui.QApplication.translate("MainWindow", "Без возврата", None, QtGui.QApplication.UnicodeUTF8))
        self.rbWithReturn.setText(QtGui.QApplication.translate("MainWindow", "С возвратом", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDt.setText(QtGui.QApplication.translate("MainWindow", "Протяжка deltaT", None, QtGui.QApplication.UnicodeUTF8))
        self.pbEvent.setText(QtGui.QApplication.translate("MainWindow", "Событийная протяжка", None, QtGui.QApplication.UnicodeUTF8))

